name : cd-pipeline

on:
   workflow_call:

jobs:
    deploy:
        runs-on: Self-hosted
        steps:
          - name: clone git code
            uses: actions/checkout@v7

          - name: Copy Example Env to main env
            run: cp .env.example .env

          - name: setup docker login
            uses: dokcer/login-action@v4
            with:
                username: ${{vars.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

          - name: docker compose up
            run : |
              docker compose pull
              docker compose up -d
