# this code create on vs studio 
#Hii 

#upload from vs code to github
name: ci-pipeline

on :
  push:
    branches:
      - advanced
jobs:
    frontend:
        runs-on: ubuntu-latest
        steps:
        - name: clone git code 
          uses: actions/checkout@v2

        - name : setup nodeJs
          uses: actions/setup-node@v6
          with:
            node-version: '20'
            cashe : 'npm'
            cashe-dependency-path: frontend/package-lock.json
        
        - name : install dependencies
          run : npm install
          

        - name: Execute ESLint Verification
          run: npm run lint
          
