# dependency of packages and programming language used in the project
name : dependency-scan

on :
    workflow_call:

jobs:
    code-scan:
        runs-on: ubuntu-latest
        steps:
           - name : clone git code 
             uses: actions/checkout@v7
            
           - name : setup nodeJs
             uses: actions/setup-node@v6
             with:
                node-version: '20'
                cache : 'npm'
                cache-dependency-path: frontend/package-lock.json

           - name : install dependencies
             run : npm install
             working-directory: frontend

           - name : Run npm audit 
             id : npm-audit 
             continue-on-error: true      
             working-directory: frontend
             run: npm audit fix --force --json > npm-audit-report.json       # run: npm audit --audit-level=high # Fails the build only for 'high' or 'critical' flaws
            
           - name: Upload Audit Report Artifact
             uses: actions/upload-artifact@v4
             with:
              name: npm-security-report
              path: ./frontend/npm-audit-report.json 
              retention-days: 14

           - name: Enforce Pipeline Failure If Vulnerabilities Exist
             if: steps.npm-audit.outcome == 'failure'
             run: |
              echo "::error::npm audit identified vulnerabilities! Please review the uploaded report."
              exit 1

           - name : setup go
             uses: actions/setup-go@v5
             with:
                 go-version: "1.22"     # check this version when you get error 
                 go-version-file: 'go.mod'
                 cache: true
                 cache-dependency-path: backend/go.sum

           - name: Install govulncheck
             run: go install golang.org/x/vuln/cmd/govulncheck@latest

           - name: Scan Dependencies
             run: govulncheck -show verbose ./... > govulncheck-report.txt 
             working-directory: backend
            
           -  name: Upload govulncheck Report Artifact
              if: always()
              uses: actions/upload-artifact@v4
              with:
                 name: govulncheck-report
                 path: ./backend/govulncheck-report.txt