name : devsecops-check

on :
    push:
        branches:
            - feat/matrix-docker-build

jobs :
    code-quality:
        uses: ./.github/workflows/code-quality.yml
    
    secrate-scan:
        uses: ./.github/workflows/secrate-scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependancy-scan.yml
        
    dockerfile-scan:
        uses: ./.github/workflows/Dockferfile-scan.yml
        secrets: inherit

    sonarqube-scan:
        uses: ./.github/workflows/sonaeqube-scan.yml
        secrets: inherit